useGroupedVersion: true

version_info_list:
  - value: latest version(3.2.0)
  - value: 3.x
    child: 
      - 3.0.30
      - 3.0.20
      - 3.0.10
      - 3.0.0
  - value: 2.x
    child:
      - 2.2.20
      - 2.2.11
      - 2.2.10
      - 2.2.0
      - 2.0.0
  - value: 1.x
    child:
      - 1.2.1
      - 1.2
      - 1.0
